### ISSUE TITLE
FLAPI-187: Get Flapi into Maven Central

### ISSUE THREAD

**Issue by UnquietCode** [UnquietCode/Flapi#55]
Mostly this is just sprucing up the poms, signing the jars, and registering the UQC repo with Sonatype. Continue to deploy to UQC but link it up so that it can be pulled into central.

http://central.sonatype.org/pages/ossrh-guide.html

* [x] #200 update group name
* [x] gpg signing
* [x] deal with UnquietCode/spring-generics#2
* [x] deal with UnquietCode/JCodeModel#7

--------------------------------------------------
Imported from JIRA
Originally reported by: [UnquietCode](https://github.com/UnquietCode)

**Comment by UnquietCode** [comment]
It is done.

http://search.maven.org/#search%7Cga%7C1%7Cflapi
